#!/usr/bin/env python3
"""Single source of truth for the CP/M drive geometries (DPBs).

The Z80 BIOS and every Python tool (cpmfs.py, image builders, tests) derive
their disk parameters from here, so the two sides can never drift apart.
Run this file to (re)generate os/cpm/src/generated_dpb.inc.

Layouts (see the plan for the full derivation):
- FD 2DD: 80 cyl x 2 heads x 16 x 256B. One CP/M track = one physical
  (cyl, side); track number = cyl*2 + side. Cylinders 0-2 are the system
  area (IPL banks + boot header + CCP/BDOS/BIOS image) -> OFF=6.
- EMM MZ-1R37 640KB: 8KB tracks; tracks 0-1 (16KB) hold the warm-boot
  image -> OFF=2. CKS=0 (non-removable).
- SASI: one CP/M drive = one 8MB partition (32768 x 256B blocks). 8KB
  tracks; tracks 0-2 (24KB) hold the boot area (IPLPRO record at
  partition block 0, bank images from block 16) -> OFF=3.
"""

from __future__ import annotations

import dataclasses
import pathlib

RECORD = 128  # CP/M logical record


@dataclasses.dataclass(frozen=True)
class Geometry:
    name: str            # BIOS symbol prefix
    comment: str
    spt: int             # 128B records per track
    bsh: int             # block shift (BLS = 128 << bsh)
    dsm: int             # highest block number
    drm: int             # highest directory entry number
    al0: int
    al1: int
    cks: int             # directory check vector size ((drm+1)/4, 0=fixed)
    off: int             # reserved tracks
    total_tracks: int    # geometry extent, for tools (not part of the DPB)

    @property
    def bls(self) -> int:
        return RECORD << self.bsh

    @property
    def blm(self) -> int:
        return (self.bls // RECORD) - 1

    @property
    def exm(self) -> int:
        # EXM per the CP/M 2.2 alteration guide: (BLS/1024) - 1 halved when
        # DSM >= 256 (double-byte allocation map).
        exm = (self.bls // 1024) - 1
        if self.dsm >= 256:
            exm = (self.bls // 2048) - 1
        return exm

    @property
    def alv_bytes(self) -> int:
        return (self.dsm + 8) // 8

    @property
    def csv_bytes(self) -> int:
        return self.cks

    @property
    def data_records(self) -> int:
        return (self.total_tracks - self.off) * self.spt

    def check(self) -> None:
        blocks = self.data_records * RECORD // self.bls
        assert self.dsm == blocks - 1, (self.name, self.dsm, blocks - 1)
        dir_blocks = ((self.drm + 1) * 32 + self.bls - 1) // self.bls
        al = 0
        for i in range(dir_blocks):
            al |= 0x8000 >> i
        assert (self.al0, self.al1) == (al >> 8, al & 0xFF), self.name
        if self.cks:
            assert self.cks == (self.drm + 1) // 4, self.name


# --- FD 2DD (drives A:, B:) -------------------------------------------------
FD = Geometry(
    name="fd",
    comment="FD 2DD 80x2x16x256, cylinders 0-2 reserved for the system",
    spt=32, bsh=4, dsm=307, drm=127, al0=0xC0, al1=0x00, cks=32, off=6,
    total_tracks=160,
)

# --- EMM MZ-1R37 640KB RAM disk (drive E:) ----------------------------------
EMM = Geometry(
    name="emm",
    comment="EMM MZ-1R37 640KB, tracks 0-1 (16KB) hold the warm-boot image",
    spt=64, bsh=4, dsm=311, drm=127, al0=0xC0, al1=0x00, cks=0, off=2,
    total_tracks=80,
)

# --- SASI 8MB partition (drives C:, D:) -------------------------------------
SASI = Geometry(
    name="sasi",
    comment="SASI 8MB partition (32768 x 256B), tracks 0-2 = boot area",
    spt=64, bsh=5, dsm=2041, drm=1023, al0=0xFF, al1=0x00, cks=0, off=3,
    total_tracks=1024,
)

GEOMETRIES = (FD, EMM, SASI)

# Fixed SASI partition bases in 256-byte blocks (M3 milestone: static layout;
# the EH-SASI partition-table reader replaces this in the HDD-boot phase).
SASI_PARTITION_BLOCKS = 32768
SASI_BASE_C = 32                     # skip LBA 0-31 (partition table area)
SASI_BASE_D = SASI_BASE_C + SASI_PARTITION_BLOCKS

# FD physical mapping shared by the BIOS and the d88 builders.
FD_CYLINDERS = 80
FD_HEADS = 2
FD_SECTORS = 16
FD_SECTOR_SIZE = 256


def generate_include() -> str:
    lines = [
        "; GENERATED by os/cpm/tools/disk_geometry.py - DO NOT EDIT",
        "; DPB layout: defw spt / defb bsh,blm,exm / defw dsm,drm /",
        ";             defb al0,al1 / defw cks,off",
    ]
    for g in GEOMETRIES:
        g.check()
        lines += [
            f"; {g.comment}",
            f"dpb_{g.name}:",
            f"\tdefw {g.spt}",
            f"\tdefb {g.bsh},{g.blm},{g.exm}",
            f"\tdefw {g.dsm}",
            f"\tdefw {g.drm}",
            f"\tdefb 0{g.al0:02x}h,0{g.al1:02x}h",
            f"\tdefw {g.cks}",
            f"\tdefw {g.off}",
            f"DPB_{g.name.upper()}_ALV_BYTES:\tequ {g.alv_bytes}",
            f"DPB_{g.name.upper()}_CSV_BYTES:\tequ {max(g.csv_bytes, 1)}",
        ]
    lines += [
        f"SASI_BASE_C_LOW:\tequ 0{SASI_BASE_C & 0xFFFF:04x}h",
        f"SASI_BASE_C_HIGH:\tequ 0{SASI_BASE_C >> 16:02x}h",
        f"SASI_BASE_D_LOW:\tequ 0{SASI_BASE_D & 0xFFFF:04x}h",
        f"SASI_BASE_D_HIGH:\tequ 0{SASI_BASE_D >> 16:02x}h",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    target = pathlib.Path(__file__).resolve().parents[1] / "src" / "generated_dpb.inc"
    target.write_text(generate_include())
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
