#!/usr/bin/env python3
"""Generate the BIOS keyboard decode table (generated_keymap.inc).

Matrix facts transcribed from web_emulator/core/keyboard.h (empirically
verified against EmuZ/BASIC-M25) and .superpowers/sdd/keyboard-matrix.md:
strobe rows 0-13 on port E8h (bit4=1 selects, bits3-0 = row, bit5 must stay
1 to keep 80-column mode), data on EAh active-low.

Table layout: rows 0-13 x bits 0-7 x 2 bytes = (normal, shifted) ASCII;
0 = no character (modifiers and dead cells). CTRL is applied by the BIOS
(masks 1Fh), SHIFT selects the second byte. Letters follow BASIC-M25's
convention: unshifted = lowercase (CCP upcases commands itself).

Cursor cluster and editing keys map onto the ADM-3A control codes the
CONOUT side of the BIOS speaks: left=^H right=^L up=^K down=^J home=^^
shift+home(CLR)=^Z, so full-screen editors configured for ADM-3A work
without translation.
"""

from __future__ import annotations

import pathlib

TARGET = pathlib.Path(__file__).resolve().parents[1] / "src" / "generated_keymap.inc"

BS, TAB, LF, VT, FF, CR, ESC, US, SUB, DEL, ETX = \
    0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x1B, 0x1E, 0x1A, 0x7F, 0x03


def ch(c: str) -> int:
    return ord(c)


# (row, bit) -> (normal, shifted). Unlisted cells emit (0, 0).
KEYMAP: dict[tuple[int, int], tuple[int, int]] = {
    # row 1: tenkey upper cluster
    (1, 2): (ch("8"), ch("8")), (1, 3): (ch("9"), ch("9")),
    (1, 6): (ch("+"), ch("+")), (1, 7): (ch("-"), ch("-")),
    # row 2: tenkey 0-7
    **{(2, b): (ch(str(b)), ch(str(b))) for b in range(8)},
    # row 3: TAB SPACE CR cursors BREAK
    (3, 0): (TAB, TAB), (3, 1): (ch(" "), ch(" ")), (3, 2): (CR, CR),
    (3, 3): (VT, VT),        # up    = ^K
    (3, 4): (LF, LF),        # down  = ^J
    (3, 5): (BS, BS),        # left  = ^H
    (3, 6): (FF, FF),        # right = ^L
    (3, 7): (ETX, ETX),      # BREAK = ^C
    # row 4: / then a-g
    (4, 0): (ch("/"), ch("?")),
    **{(4, b): (ord("a") + b - 1, ord("A") + b - 1) for b in range(1, 8)},
    # rows 5-6: h-o, p-w
    **{(5, b): (ord("h") + b, ord("H") + b) for b in range(8)},
    **{(6, b): (ord("p") + b, ord("P") + b) for b in range(8)},
    # row 7: x y z ^ \ _ . ,
    (7, 0): (ch("x"), ch("X")), (7, 1): (ch("y"), ch("Y")),
    (7, 2): (ch("z"), ch("Z")),
    (7, 3): (ch("^"), ch("~")), (7, 4): (ch("\\"), ch("|")),
    (7, 5): (ch("_"), ch("_")),
    (7, 6): (ch("."), ch(">")), (7, 7): (ch(","), ch("<")),
    # row 8: 0-7 with JIS shifted symbols (SHIFT+2 = '"' verified)
    (8, 0): (ch("0"), ch("0")), (8, 1): (ch("1"), ch("!")),
    (8, 2): (ch("2"), ch('"')), (8, 3): (ch("3"), ch("#")),
    (8, 4): (ch("4"), ch("$")), (8, 5): (ch("5"), ch("%")),
    (8, 6): (ch("6"), ch("&")), (8, 7): (ch("7"), ch("'")),
    # row 9: 8 9 : ; - @ [
    (9, 0): (ch("8"), ch("(")), (9, 1): (ch("9"), ch(")")),
    (9, 2): (ch(":"), ch("*")), (9, 3): (ch(";"), ch("+")),
    (9, 4): (ch("-"), ch("=")), (9, 5): (ch("@"), ch("`")),
    (9, 6): (ch("["), ch("{")),
    # row 10: ] COPY HOME/CLR DEL BS ESC kp* kp/
    (10, 0): (ch("]"), ch("}")),
    (10, 2): (US, SUB),       # HOME = ^^ (cursor home), SHIFT = CLR = ^Z
    (10, 3): (DEL, DEL), (10, 4): (BS, BS), (10, 5): (ESC, ESC),
    (10, 6): (ch("*"), ch("*")), (10, 7): (ch("/"), ch("/")),
    # rows 11-13: modifiers / IME / HELP / ALGO carry no character
}

MOD_ROW = 11
MOD_GRAPH, MOD_LOCK, MOD_SHIFT, MOD_KANA, MOD_CTRL = 0, 1, 2, 3, 4


def main() -> int:
    lines = [
        "; GENERATED by os/cpm/tools/gen_keymap.py - DO NOT EDIT",
        "; 14 rows x 8 bits x (normal, shifted); 0 = no character",
        f"KEYMAP_ROWS:\tequ 14",
        f"KEY_MOD_ROW:\tequ {MOD_ROW}",
        f"KEY_MOD_SHIFT_MASK:\tequ 0{1 << MOD_SHIFT:02x}h",
        f"KEY_MOD_CTRL_MASK:\tequ 0{1 << MOD_CTRL:02x}h",
        "keymap_table:",
    ]
    for row in range(14):
        pairs = []
        for bit in range(8):
            normal, shifted = KEYMAP.get((row, bit), (0, 0))
            pairs.append(f"0{normal:02x}h,0{shifted:02x}h")
        lines.append(f"\tdefb {','.join(pairs)} ; row {row}")
    TARGET.write_text("\n".join(lines) + "\n")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
