#!/usr/bin/env python3
"""Generate the PCG console font include from the vendored font8x8.

Source: vendor/font8x8/font8x8_basic.h (public domain, IBM PD VGA lineage;
fetched by fetch_cpm22.py). It stores each glyph as 8 row bytes with the
LEFTMOST pixel in bit 0. The MZ-2500 text renderer reads PCG glyph rows
with the leftmost pixel in bit 7, so every byte is bit-reversed here.

Output: src/generated_font.inc - 96 glyphs (20h-7Fh) x 8 bytes,
loaded by the cold-boot overlay into PCG page 0 at code*8 (F7h bit0=1
selects the 8-line/256-character font layout).
"""

from __future__ import annotations

import pathlib
import re

REPO = pathlib.Path(__file__).resolve().parents[1]
SOURCE = REPO / "vendor" / "font8x8" / "font8x8_basic.h"
TARGET = pathlib.Path(__file__).resolve().parents[1] / "src" / "generated_font.inc"

FIRST, LAST = 0x20, 0x7F


def parse_glyphs(text: str) -> list[list[int]]:
    rows = re.findall(r"\{\s*((?:0x[0-9A-Fa-f]{2}\s*,\s*){7}0x[0-9A-Fa-f]{2})\s*\}",
                      text)
    glyphs = [[int(v, 16) for v in re.findall(r"0x[0-9A-Fa-f]{2}", row)]
              for row in rows]
    if len(glyphs) < 128:
        raise SystemExit(f"unexpected glyph count {len(glyphs)} in {SOURCE}")
    return glyphs


def reverse_bits(value: int) -> int:
    return int(f"{value:08b}"[::-1], 2)


def main() -> int:
    if not SOURCE.is_file():
        raise SystemExit(f"{SOURCE} missing - run tools/fetch_cpm22.py")
    glyphs = parse_glyphs(SOURCE.read_text())
    lines = [
        "; GENERATED by tools/gen_font.py from vendor/font8x8 - DO NOT EDIT",
        f"FONT_FIRST_CODE:\tequ 0{FIRST:02x}h",
        f"FONT_GLYPH_COUNT:\tequ {LAST - FIRST + 1}",
        "font_data:",
    ]
    for code in range(FIRST, LAST + 1):
        data = ",".join(f"0{reverse_bits(b):02x}h" for b in glyphs[code])
        label = chr(code) if 0x20 < code < 0x7F else f"{code:02x}h"
        lines.append(f"\tdefb {data} ; {label}")
    lines.append("FONT_DATA_SIZE:\tequ $-font_data")
    TARGET.write_text("\n".join(lines) + "\n")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
