#!/usr/bin/env python3
"""Build MIGRATE.COM and a CP/M Plus boot FD for real-machine migration."""
import json, pathlib, subprocess, sys, zlib, zipfile, hashlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tools'))
from d88 import D88Image
from cpmfs import CpmFilesystem,D88CpmAdapter
import disk_geometry as dg
from make_boot_d88 import DRI_UTILITIES
from make_format import build_format

def main():
    build=ROOT/'build'; src=ROOT/'src/migration'
    layout=json.loads((build/'cpm_layout.json').read_text())
    payload=bytearray(b''.join((build/f'cpm_bank{x:02x}.bin').read_bytes() for x in layout['banks']))
    patch=layout['boot_drive_default']-0x8000;payload[patch]=2
    files=list(DRI_UTILITIES)+['PUTSYS.COM']
    paths=[ROOT/'vendor/cpm3/bin'/n.lower() if n!='PUTSYS.COM' else build/'putsys.com' for n in files]
    blocks=sum((p.stat().st_size+4095)//4096 for p in paths)
    entries=sum(max(1,(p.stat().st_size+32767)//32768) for p in paths)
    (src/'generated.h').write_text('// Generated by make_migration_disk.py.\n'+
        f'#define INSTALL_BLOCKS {blocks}\n#define INSTALL_ENTRIES {entries}\n#define INSTALL_COUNT {len(files)}\n'+
        f'#define BOOT_PATCH_RECORD {32+patch//128}\n#define BOOT_PATCH_OFFSET {patch%128}\n#define BOOT_CRC 0x{zlib.crc32(payload):08x}UL\n'+
        'static const char install_names[][13]={'+','.join(json.dumps(n) for n in files)+'};\n')
    subprocess.run(['sdasz80','-o',str(build/'migcrt.rel'),str(src/'crt0.s')],check=True)
    for name in ('io','main'):
        subprocess.run(['sdcc','-mz80','--std-c99','--opt-code-size','-c',str(src/f'{name}.c'),'-o',str(build/f'mig_{name}.rel')],check=True)
    subprocess.run(['sdcc','-mz80','--no-std-crt0','--code-loc','0x0109','--data-loc','0x8000',str(build/'migcrt.rel'),str(build/'mig_io.rel'),str(build/'mig_main.rel'),'-o',str(build/'migrate.ihx')],check=True)
    memory={}
    for line in (build/'migrate.ihx').read_text().splitlines():
        rec=bytes.fromhex(line[1:]);assert sum(rec)&255==0
        if rec[3]==0:
            at=int.from_bytes(rec[1:3],'big')
            memory.update((at+i,b) for i,b in enumerate(rec[4:4+rec[0]]))
    assert min(memory)==256 and max(memory)<0x8000,'code/initializers overlap data'
    import re
    maptext=(build/'migrate.map').read_text()
    data=re.search(r'^_DATA\s+([0-9A-F]+)\s+([0-9A-F]+)',maptext,re.M)
    assert data and sum(int(x,16) for x in data.groups())<=0xDD00,'data overlaps stack'
    com=bytes(memory.get(i,0) for i in range(256,max(memory)+1))
    (build/'migrate.com').write_bytes(com)
    formatter=build_format(ROOT)
    image=D88Image(bytearray((build/'cpm_boot.d88').read_bytes()))
    CpmFilesystem(D88CpmAdapter(image,dg.FD)).add_file('MIGRATE.COM',com)
    CpmFilesystem(D88CpmAdapter(image,dg.FD)).add_file('FORMAT.COM',formatter)
    (build/'cpm_migrate.d88').write_bytes(image.data)
    # This template supplies physical 2DD formatting; backup writes a raw volume.
    (build/'migration_blank.d88').write_bytes((build/'cpm_data.d88').read_bytes())
    kit={
        'cpm_migrate.d88': build/'cpm_migrate.d88',
        'migration_blank.d88': build/'migration_blank.d88',
        'MIGRATE.COM': build/'migrate.com',
        'FORMAT.COM': build/'format.com',
        'docs/migration.md': ROOT/'docs/migration.md',
        'tools/migration_archive.py': ROOT/'tools/migration_archive.py',
        'tools/d88.py': ROOT/'tools/d88.py',
        'LICENSES.md': ROOT/'LICENSES.md',
        'LICENSE': ROOT/'LICENSE',
        'licenses/CPM.txt': ROOT/'vendor/cpm3/LICENSE.txt',
    }
    with zipfile.ZipFile(build/'mz2500-migration-kit.zip','w',zipfile.ZIP_DEFLATED) as archive:
        for name,path in kit.items(): archive.write(path,name)
        archive.writestr('SHA256SUMS', ''.join(hashlib.sha256(path.read_bytes()).hexdigest()+'  '+name+'\n' for name,path in kit.items()))
    print(f'MIGRATE.COM {len(com)} bytes; install reserve {blocks} blocks / {entries} entries')
    print('Created build/cpm_migrate.d88 and build/migration_blank.d88')
if __name__=='__main__':main()
