#!/usr/bin/env python3
"""Build the bootable MZ-2500 CP/M 2.2 floppy (d88).

Pipeline:
1. regenerate the derived includes (DPB / keymap / font)
2. convert the vendored CCP/BDOS to z80asm syntax at the 58K origins
3. assemble boot unit (stub+font+coldinit), CCP, BDOS, BIOS
4. splice the two 8KB IPL bank images:
     bank06 (C000h-DFFFh) = boot unit | CCP | BDOS front
     bank07 (E000h-FFFFh) = BDOS tail | BIOS
5. write a blank 2DD d88: IPLPRO header (C0/H1/R1), bank sources in the
   firmware's physical order, CP/M filesystem from track 6
6. inject the DRI utilities from vendor/cpm22/bin (skipped with a warning
   when the vendor tree has not been fetched)

Every layout number is anchored to disk_geometry.py and the BIOS equates;
the label file of each assembly is checked so drift fails the build.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

PROJECT = pathlib.Path(__file__).resolve().parents[1]
SRC = PROJECT / "src"
BUILD = PROJECT / "build"
VENDOR = PROJECT / "vendor" / "cpm22"
sys.path.insert(0, str(PROJECT / "tools"))

from d88 import D88Image, SECTOR_SIZE, make_blank_d88  # noqa: E402
import disk_geometry as dg  # noqa: E402
import cpmfs  # noqa: E402

CCP_BASE = 0xD200
BDOS_BASE = 0xDA00
BIOS_BASE = 0xE800
BOOT_BASE = 0xC000
BANK_SIZE = 0x2000
IPL_DEST_BANKS = (0x06, 0x07)
IPL_CPU_BLOCKS = (0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06)

DRI_UTILITIES = ("PIP.COM", "STAT.COM", "ED.COM", "ASM.COM", "DDT.COM",
                 "SUBMIT.COM", "DUMP.COM", "LOAD.COM", "XSUB.COM")


def run(cmd: list[str], cwd: pathlib.Path) -> str:
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout + proc.stderr)
        raise SystemExit(f"command failed: {' '.join(cmd)}")
    return proc.stdout + proc.stderr


def assemble(source: pathlib.Path, output: pathlib.Path,
             cwd: pathlib.Path) -> dict[str, int]:
    text = run(["z80asm", "-L", "-o", str(output), str(source)], cwd)
    labels = {}
    for match in re.finditer(r"^([A-Za-z_][\w]*):\s*equ\s*\$([0-9A-Fa-f]+)",
                             text, re.MULTILINE):
        labels[match.group(1)] = int(match.group(2), 16)
    return labels


def build_binaries() -> tuple[bytes, bytes]:
    BUILD.mkdir(exist_ok=True)
    run(["python3", "tools/disk_geometry.py"], PROJECT)
    run(["python3", "tools/gen_keymap.py"], PROJECT)
    run(["python3", "tools/gen_font.py"], PROJECT)

    run(["python3", "tools/convert_cpm22.py",
         "--input", str(VENDOR / "src" / "ccp.asm"),
         "--output", str(BUILD / "ccp_z80.asm"),
         "--origin", hex(CCP_BASE)], PROJECT)
    run(["python3", "tools/convert_cpm22.py",
         "--input", str(VENDOR / "src" / "bdos.asm"),
         "--output", str(BUILD / "bdos_z80.asm"),
         "--origin", hex(BDOS_BASE),
         "--define", f"bios={hex(BIOS_BASE)}"], PROJECT)

    boot_labels = assemble(SRC / "boot.asm", BUILD / "boot.bin", SRC)
    bios_labels = assemble(SRC / "bios.asm", BUILD / "bios.bin", SRC)
    # PUTSYS needs the address of the boot-drive byte so a floppy->HDD
    # system copy can re-apply the "boot to C:" patch on the hard disk.
    (SRC / "generated_putsys.inc").write_text(
        "; GENERATED by make_boot_d88.py - DO NOT EDIT\n"
        f"BOOT_DRIVE_BYTE_ADDR:\tequ 0{bios_labels['boot_drive_default']:04x}h\n")
    assemble(SRC / "putsys.asm", BUILD / "putsys.com", SRC)
    assemble(BUILD / "ccp_z80.asm", BUILD / "ccp.bin", BUILD)
    bdos_labels = assemble(BUILD / "bdos_z80.asm", BUILD / "bdos.bin", BUILD)

    boot = (BUILD / "boot.bin").read_bytes()
    bios = bytearray((BUILD / "bios.bin").read_bytes())
    ccp = (BUILD / "ccp.bin").read_bytes()
    bdos = bytearray((BUILD / "bdos.bin").read_bytes())

    # --- documented divergence from the stock BDOS (one JMP target) ---
    # Function 13 (disk reset, run on every warm boot) hard-selects drive
    # A:, spinning the floppy up before every prompt on a hard-disk
    # system. Redirect its final "jp select" through a BIOS stub that
    # re-selects the CURRENT drive ((0004h) & 0Fh) instead - identical to
    # stock whenever the current drive is A:.
    func13 = bdos_labels["func13"] - BDOS_BASE
    select_addr = bdos_labels["select"]
    curdsk = bdos_labels["curdsk"]
    hook = bios_labels["bdos_reset_hook"]
    jmp_select = bytes([0xC3, select_addr & 0xFF, select_addr >> 8])
    window = bdos[func13:func13 + 0x20]
    pos = window.find(jmp_select)
    if pos < 0 or window.find(jmp_select, pos + 1) >= 0:
        raise SystemExit("func13's jp select not found exactly once")
    bdos[func13 + pos:func13 + pos + 3] = \
        bytes([0xC3, hook & 0xFF, hook >> 8])
    stub = bytes([0x3A, 0x04, 0x00,              # ld a,(0004h)
                  0xE6, 0x0F,                    # and 0fh
                  0x32, curdsk & 0xFF, curdsk >> 8,   # ld (curdsk),a
                  0xC3, select_addr & 0xFF, select_addr >> 8])  # jp select
    hook_off = hook - BIOS_BASE
    if bytes(bios[hook_off:hook_off + 16]) != b"\x00" * 16:
        raise SystemExit("bdos_reset_hook area is not empty")
    bios[hook_off:hook_off + len(stub)] = stub
    bios = bytes(bios)
    bdos = bytes(bdos)

    # layout guards
    if len(boot) > CCP_BASE - BOOT_BASE:
        raise SystemExit(f"boot unit overflows into CCP ({len(boot):#x} bytes)")
    if len(ccp) > 0x800:
        raise SystemExit("CCP larger than 800h")
    if len(bdos) > 0xE00:
        raise SystemExit("BDOS larger than E00h")
    if BIOS_BASE + len(bios) > 0x10000:
        raise SystemExit(f"BIOS overflows 64KB ({len(bios):#x} bytes)")
    if bios_labels.get("BIOS_END", 0) > 0x10000:
        raise SystemExit("BIOS_END beyond top of memory")
    if boot_labels.get("coldinit", 0) != 0xC400:
        raise SystemExit("cold-init overlay is not at C400h")

    ccp = ccp.ljust(0x800, b"\0")
    bdos = bdos.ljust(0xE00, b"\0")
    boot = boot.ljust(CCP_BASE - BOOT_BASE, b"\0")
    bios = bios.ljust(0x1800, b"\0")

    bank06 = boot + ccp + bdos[:0x600]
    bank07 = bdos[0x600:] + bios
    assert len(bank06) == BANK_SIZE and len(bank07) == BANK_SIZE
    # bank copies + layout for the hard-disk image builder
    (BUILD / "cpm_bank06.bin").write_bytes(bank06)
    (BUILD / "cpm_bank07.bin").write_bytes(bank07)
    import json
    (BUILD / "cpm_layout.json").write_text(json.dumps({
        "bios_base": BIOS_BASE,
        "boot_drive_default": bios_labels["boot_drive_default"],
    }, indent=1))
    print(f"boot+font+coldinit {len(boot.rstrip(bytes([0]))):#6x} bytes, "
          f"bios {bios_labels['BIOS_END'] - BIOS_BASE:#6x} bytes "
          f"(end {bios_labels['BIOS_END']:#06x})")
    return bank06, bank07


def make_ipl_header() -> bytes:
    header = bytearray(SECTOR_SIZE)
    header[0] = 0x01
    header[1:7] = b"IPLPRO"
    header[7:19] = b"CP/M-2.2   \r"
    header[0x18:0x1A] = BOOT_BASE.to_bytes(2, "little")
    header[0x1E:0x20] = (0x0010).to_bytes(2, "little")
    header[0x20:0x21 + len(IPL_DEST_BANKS)] = bytes((*IPL_DEST_BANKS, 0xFF))
    header[0x30:0x37] = bytes(IPL_CPU_BLOCKS)
    return bytes(header)


def write_ipl_banks(image: D88Image, payloads: tuple[bytes, ...]) -> None:
    """Firmware physical source order: bank n = C(n)/H0 + C(n+1)/H1."""
    for index, payload in enumerate(payloads):
        assert len(payload) == BANK_SIZE
        for half, start_lba in enumerate((index * 32, index * 32 + 48)):
            half_start = half * (BANK_SIZE // 2)
            for sector in range(16):
                start = half_start + sector * SECTOR_SIZE
                image.write_sector(start_lba + sector,
                                   payload[start:start + SECTOR_SIZE])


def build_disk(output: pathlib.Path, with_files: bool) -> None:
    bank06, bank07 = build_binaries()
    image = make_blank_d88("CPM22")
    image.write_sector(16, make_ipl_header())
    write_ipl_banks(image, (bank06, bank07))

    fs = cpmfs.CpmFilesystem(cpmfs.D88CpmAdapter(image, dg.FD))
    fs.format()
    injected = 0
    if with_files:
        for name in DRI_UTILITIES:
            path = VENDOR / "bin" / name
            if not path.is_file():
                print(f"note: {name} not in vendor/cpm22/bin - "
                      "run os/cpm/tools/fetch_cpm22.py; building without it")
                continue
            fs.add_file(name, path.read_bytes())
            injected += 1
        fs.add_file("PUTSYS.COM", (BUILD / "putsys.com").read_bytes())
        injected += 1
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(image.data)
    print(f"wrote {output} ({injected} DRI files injected)")


def build_data_disk(output: pathlib.Path, groups: tuple[str, ...] = ()) -> None:
    """A CP/M-formatted 2DD with no system tracks; optionally carrying
    tool groups so real machines can PIP them onto the hard disk."""
    import fetch_tools
    image = make_blank_d88("CPMDATA")
    fs = cpmfs.CpmFilesystem(cpmfs.D88CpmAdapter(image, dg.FD))
    fs.format()
    count = 0
    for group in groups:
        for path in fetch_tools.group_files(group):
            if path.is_file():
                fs.add_file(path.name, path.read_bytes())
                count += 1
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(image.data)
    label = f"{count} files" if groups else "formatted, empty"
    print(f"wrote {output} ({label})")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(BUILD / "cpm_boot.d88"))
    parser.add_argument("--no-files", action="store_true",
                        help="skip the DRI utility injection")
    parser.add_argument("--data-disk", action="store_true",
                        help="build a formatted, system-less data disk instead")
    parser.add_argument("--collection", choices=["tools", "langs1", "langs2"],
                        help="data disk carrying tool groups (implies "
                             "--data-disk): tools=DEV+CBASIC, "
                             "langs1=Pascal/MT+, langs2=PL/I-80+BDS C")
    args = parser.parse_args()
    collections = {
        "tools": ("DEV", "BASIC"),
        "langs1": ("PASCAL",),
        "langs2": ("PLI", "BDSC"),
    }
    if args.collection:
        build_data_disk(pathlib.Path(args.output), collections[args.collection])
    elif args.data_disk:
        build_data_disk(pathlib.Path(args.output))
    else:
        build_disk(pathlib.Path(args.output), not args.no_files)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
