#!/usr/bin/env python3
"""Build a native IPLPRO CP/M Plus system (banked DRI BDOS)."""
from __future__ import annotations
import argparse
import json
import pathlib
import re
import subprocess
import sys
PROJECT = pathlib.Path(__file__).resolve().parents[1]
SRC = PROJECT / "src"
BUILD = PROJECT / "build"
VENDOR = PROJECT / "vendor" / "cpm3"
sys.path.insert(0, str(PROJECT / "tools"))
from d88 import D88Image, SECTOR_SIZE, make_blank_d88
import disk_geometry as dg
import cpmfs
from relocate_cpm3 import relocate_banked

BDOS_BASE = 0xE200
BIOS_BASE = 0xE800
BOOT_BASE = 0x8000
CCP_IMAGE = 0xA500
CCP_SIZE = 0xC80
BANK_SIZE = 0x2000
IPL_DEST_BANKS = (0x0C, 0x0D, 0x0E, 0x07)
IPL_CPU_BLOCKS = (8, 9, 10, 11, 12, 13, 14)
DRI_UTILITIES = ("CCP.COM", "PIP.COM", "ED.COM", "SUBMIT.COM", "DUMP.COM",
                 "DIR.COM", "TYPE.COM", "ERASE.COM", "RENAME.COM", "SHOW.COM",
                 "SET.COM", "SETDEF.COM", "DEVICE.COM", "DATE.COM", "HELP.COM",
                 "HELP.HLP", "HEXCOM.COM", "SID.COM", "SAVE.COM", "GET.COM",
                 "PUT.COM", "GENCOM.COM")

def run(cmd: list[str], cwd: pathlib.Path) -> str:
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout + proc.stderr)
        raise SystemExit(f"command failed: {' '.join(cmd)}")
    return proc.stdout + proc.stderr


def assemble(source: pathlib.Path, output: pathlib.Path,
             cwd: pathlib.Path) -> dict[str, int]:
    text = run(["z80asm", "-L", "-o", str(output), str(source)], cwd)
    labels = {}
    for match in re.finditer(r"^([A-Za-z_][\w]*):\s*equ\s*\$([0-9A-Fa-f]+)",
                             text, re.MULTILINE):
        labels[match.group(1)] = int(match.group(2), 16)
    return labels


def build_binaries() -> tuple[bytes, ...]:
    from fetch_cpm3 import verify_binaries
    verify_binaries()
    BUILD.mkdir(exist_ok=True)
    for script in ("disk_geometry.py", "gen_keymap.py", "gen_font.py"):
        run([sys.executable, f"tools/{script}"], PROJECT)
    boot_labels = assemble(SRC / "boot.asm", BUILD / "boot.bin", SRC)
    bios_labels = assemble(SRC / "bios.asm", BUILD / "bios.bin", SRC)
    (SRC / "generated_core.inc").write_text(
        "; GENERATED by make_boot_d88.py\n" + "".join(
            f"CORE_{name}: equ 0{value:04x}h\n" for name,value in bios_labels.items()))
    common_labels = assemble(SRC / "bios_common.asm", BUILD / "bios_common.bin", SRC)
    (SRC / "generated_putsys.inc").write_text(
        "; GENERATED by make_boot_d88.py - DO NOT EDIT\n"
        f"BOOT_DRIVE_BYTE_ADDR:\tequ 0{bios_labels['boot_drive_default']:04x}h\n")
    assemble(SRC / "putsys.asm", BUILD / "putsys.com", SRC)
    bdos, bnkbdos = relocate_banked((VENDOR / "bin/resbdos3.spr").read_bytes(),
                                   (VENDOR / "bin/bnkbdos3.spr").read_bytes())
    ccp = (VENDOR / "bin/ccp.com").read_bytes()
    boot = (BUILD / "boot.bin").read_bytes()
    bios = (BUILD / "bios.bin").read_bytes()
    if len(ccp) != CCP_SIZE:
        raise SystemExit("CCP size changed; review the BIOS cache contract")
    common = (BUILD / "bios_common.bin").read_bytes()
    if len(boot) > 0x500 or 0x8500+len(bios) > CCP_IMAGE:
        raise SystemExit("boot/core BIOS overflow")
    if CCP_IMAGE + len(ccp) > 0xB200 or 0xB200+len(bnkbdos) != 0xE000:
        raise SystemExit("bank-0 BDOS/cache overlap")
    if BDOS_BASE+len(bdos) != BIOS_BASE or BIOS_BASE+len(common) > 0x10000:
        raise SystemExit("common memory overflow")
    payload = bytearray(0x8000)
    for address,data in ((BOOT_BASE,boot),(0x8500,bios),(CCP_IMAGE,ccp),
                         (0xB200,bnkbdos),(BDOS_BASE,bdos),(BIOS_BASE,common)):
        payload[address-BOOT_BASE:address-BOOT_BASE+len(data)] = data
    banks = tuple(bytes(payload[i:i+BANK_SIZE]) for i in range(0,len(payload),BANK_SIZE))
    for bank,data in zip(IPL_DEST_BANKS,banks):
        (BUILD / f"cpm_bank{bank:02x}.bin").write_bytes(data)
    (BUILD / "bnkbdos.bin").write_bytes(bnkbdos)
    (BUILD / "bdos.bin").write_bytes(bdos)
    (BUILD / "cpm_layout.json").write_text(json.dumps({
        "version": "3.1.0", "bdos_version": "3.1", "banked": True,
        "bdos_base": BDOS_BASE, "bios_base": BIOS_BASE,
        "boot_drive_default": bios_labels['boot_drive_default'],
        "banks": list(IPL_DEST_BANKS), "labels": bios_labels, "common_labels": common_labels,
    }, indent=2) + "\n")
    print(f"CP/M Plus: BDOS {BDOS_BASE:04X}, BIOS {BIOS_BASE:04X}, common end {common_labels['COMMON_END']:04X}")
    return banks


def make_ipl_header() -> bytes:
    header = bytearray(SECTOR_SIZE)
    header[0] = 0x01
    header[1:7] = b"IPLPRO"
    header[7:19] = b"CP/M-PLUS  \r"
    header[0x18:0x1A] = BOOT_BASE.to_bytes(2, "little")
    header[0x1E:0x20] = (0x0010).to_bytes(2, "little")
    header[0x20:0x21 + len(IPL_DEST_BANKS)] = bytes((*IPL_DEST_BANKS, 0xFF))
    header[0x30:0x37] = bytes(IPL_CPU_BLOCKS)
    return bytes(header)


def write_ipl_banks(image: D88Image, payloads: tuple[bytes, ...]) -> None:
    """Firmware physical source order: bank n = C(n)/H0 + C(n+1)/H1."""
    for index, payload in enumerate(payloads):
        assert len(payload) == BANK_SIZE
        for half, start_lba in enumerate((index * 32, index * 32 + 48)):
            half_start = half * (BANK_SIZE // 2)
            for sector in range(16):
                start = half_start + sector * SECTOR_SIZE
                image.write_sector(start_lba + sector,
                                   payload[start:start + SECTOR_SIZE])


def build_disk(output: pathlib.Path, with_files: bool) -> None:
    banks = build_binaries()
    image = make_blank_d88("CPMPLUS")
    image.write_sector(16, make_ipl_header())
    write_ipl_banks(image, banks)

    fs = cpmfs.CpmFilesystem(cpmfs.D88CpmAdapter(image, dg.FD))
    fs.format()
    injected = 0
    if with_files:
        for name in DRI_UTILITIES:
            path = VENDOR / "bin" / name.lower()
            if not path.is_file():
                raise SystemExit(f"missing {path}; run make fetch")
            fs.add_file(name, path.read_bytes())
            injected += 1
        fs.add_file("PUTSYS.COM", (BUILD / "putsys.com").read_bytes())
        injected += 1
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(image.data)
    print(f"wrote {output} ({injected} DRI files injected)")


def build_data_disk(output: pathlib.Path, groups: tuple[str, ...] = ()) -> None:
    """A CP/M-formatted 2DD with no system tracks; optionally carrying
    tool groups so real machines can PIP them onto the hard disk."""
    import fetch_tools
    image = make_blank_d88("CPMDATA")
    fs = cpmfs.CpmFilesystem(cpmfs.D88CpmAdapter(image, dg.FD))
    fs.format()
    count = 0
    for group in groups:
        for path in fetch_tools.group_files(group):
            if path.is_file():
                fs.add_file(path.name, path.read_bytes())
                count += 1
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(image.data)
    label = f"{count} files" if groups else "formatted, empty"
    print(f"wrote {output} ({label})")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(BUILD / "cpm_boot.d88"))
    parser.add_argument("--no-files", action="store_true",
                        help="skip the DRI utility injection")
    parser.add_argument("--data-disk", action="store_true",
                        help="build a formatted, system-less data disk instead")
    parser.add_argument("--collection", choices=["tools", "langs1", "langs2"],
                        help="data disk carrying tool groups (implies "
                             "--data-disk): tools=DEV+CBASIC, "
                             "langs1=Pascal/MT+, langs2=PL/I-80+BDS C")
    args = parser.parse_args()
    collections = {
        "tools": ("DEV", "BASIC"),
        "langs1": ("PASCAL",),
        "langs2": ("PLI", "BDSC"),
    }
    if args.collection:
        build_data_disk(pathlib.Path(args.output), collections[args.collection])
    elif args.data_disk:
        build_data_disk(pathlib.Path(args.output))
    else:
        build_disk(pathlib.Path(args.output), not args.no_files)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
